# Generated by Django 5.0.7 on 2024-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Email')),
                ('password', models.CharField(db_index=True, max_length=100, verbose_name='Password')),
                ('token', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Token')),
                ('token_expires_at', models.DateTimeField(blank=True, verbose_name='Token Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
